### ISSUE TITLE
Where is the file "train_data.csv"?

### ISSUE THREAD

**Issue by renxiaosa00** [xq141839/DCSAU-Net#10]

**Comment by xq141839** [comment]
Hello, due to the capacity limitation of GitHub, we have not uploaded any datasets. You should organise your dataset or download open-access datasets by yourself. Make sure your dataset has the same structure as README, and then you can generate train_data.csv using data_split_csv.py.

**Comment by renxiaosa00** [comment]
ok,thank you～

在 2022-12-09 12:52:48，Nanami ***@***.***> 写道：


Hello, due to the capacity limitation of GitHub, we have not uploaded any datasets. You should organise your dataset or download open-access datasets by yourself. Make sure your dataset has the same structure as README, and then you can generate train_data.csv using data_split_csv.py.
