### ISSUE TITLE
isic预测输出全白

### ISSUE THREAD

**Issue by wjzhang-ty** [xq141839/DCSAU-Net#12]
我在尝试运行isic2018数据集，loss用默认的dice。
训练似乎是无效的，网络输出全白图像。
看到类似issue中提到修改1-dice后正常，我查看了loss.py 68行已经是1-dice了，可以给我一些排查方向吗？
谢谢大佬！

**Comment by xq141839** [comment]
你可以看看你训练的时候loss和acc是不是正常的上升或者下降。其次可以看一下你的数据集的输入和相应的分割mask是不是对应，以及mask的格式是不是正确，所需要的输出类别是否正确（二分类的模型输出class=1，用sigmoid）。如果训练没问题那就要看看你在测试的时候，测试的输入数据是否正确（维度啊预处理是否和训练集一样，等等）。希望这些建议对你有所帮助！

**Comment by wjzhang-ty** [comment]
找到了，数据增强导致的。
isic2018的input尺寸为：B 3 H W.  mask尺寸为：B 1 H W
增强后input最大值2.+    mask最大值还是255，没有归一化
