### ISSUE TITLE
RuntimeWarning: Mean of empty slice.

### ISSUE THREAD

**Issue by xueyue-hd** [xq141839/DCSAU-Net#16]
出现上述问题可能的原因是：data_split_csv.py 的数据集划分失败所致。
下面的代码路径要设置为数据集的图片文件夹路径，而非数据集文件夹路径。原始代码的提示写错了，下面是修改后的。
parser.add_argument('--dataset', type=str, default='../datasets/DSB2018/image', help='the path of images')
同时也要注意，在训练代码处的数据集参数只需要写数据集文件夹的路径，我怀疑作者把两个地方的参数提示写反了

**Comment by xq141839** [comment]
非常感谢您的指正，我会把您修改后的代码放上去
