### ISSUE TITLE
向您请教关于brats2021数据处理的问题

### ISSUE THREAD

**Issue by 18985459173** [xq141839/DCSAU-Net#18]
您好！我看了您的文章，写得非常nice！但在brats2021数据处理这一块还有疑问，在文中您是使用了brats2021训练集的所有病例1251例，然后将900例作为训练，226例验证，125例测试，那么在由大小为（240，240，155）的nii文件中，你是取了所有的2d切片吗？还是只取这155张中的部分数据？2d的训练、验证、测试数据量分别是多少张2D图像呀？

**Comment by xq141839** [comment]
您好，非常感谢您对我们工作的认可，brats2021数据集中，我们用flair数据进行训练。训练集我们取所有的2d切片，所以训练集将会有900x155张2d图。不过我的建议是把框架转成3d后再进行训练，当然这个工作我们也在进行中。

**Comment by xq141839** [comment]
应该是ET/ED/NCR三类的平均值，我是从这里下的数据集：[https://www.kaggle.com/datasets/dschettler8845/brats-2021-task1](url)
