### ISSUE TITLE
请教一个问题：数据集划分

### ISSUE THREAD

**Issue by xueyue-hd** [xq141839/DCSAU-Net#19]
作者您好，我在使用代码的时候发现训练的时候的验证集与测试的时候的验证集对不上，大部分验证集在训练时作为训练集参与训练，在执行eval_binary.py的时候这些参与训练的验证集（训练集）又作为验证集去验证结果，导致验证后的结果会比真实结果高出一大截。
![Snipaste_2023-06-23_22-17-50](https://github.com/xq141839/DCSAU-Net/assets/93185312/d1e8c4ad-3bd0-4f44-843b-9f7ef1a1d4ac)

**Comment by xueyue-hd** [comment]
上图中的控制带打印的就是训练时实际使用的验证集，与提前划分好的验证集不一致

**Comment by xq141839** [comment]
你好，你好提前划分的是测试集和训练集，验证集是从训练集中取出来的。数据集总共划分为三份。验证集当然会和测试集不同。

**Comment by xueyue-hd** [comment]
可是训练代码里面的数据确实是从所有数据中取出来的，并没有专门从提前划分的训练集中取出。

**Comment by xq141839** [comment]
![image](https://github.com/xq141839/DCSAU-Net/assets/98734126/ee823c3a-34d2-4f32-b7b7-9e198ad44d97)
可能你是直接用数据分割文件出来的csv了吧，这个train.py理论上需要单独把训练的csv给拷贝出来。可以再加一行代码就行

**Comment by xueyue-hd** [comment]
原来是这样，我搞错了，谢谢作者解答&nbsp;


我是何东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 上午8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xq141839/DCSAU-Net] 请教一个问题：数据集划分 (Issue #19)





 

 可能你是直接用数据分割文件出来的csv了吧，这个train.py理论上需要单独把训练的csv给拷贝出来。可以再加一行代码就行

**Comment by xq141839** [comment]
没事哒，我也是又原代码更新了一下，把那两个代码输出和输入给连了一下：）
