### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by jiokul** [xq141839/DCSAU-Net#2]
我使用这个网络分割眼底图像视盘，按照README中的流程做完后iou仅达到了0.04，同时loss并没有明显下降，我想请教一下是我还需要调整额外的参数吗

**Comment by jiokul** [comment]
iou0.04因为预测的是全白
并没有成功预测

**Comment by xq141839** [comment]
你有微信或者qq吗，可以讨论一下

**Comment by xq141839** [comment]
或者你可以先检查一下你的数据集创建方式是不是正确的

**Comment by jiokul** [comment]
我的qq：1416036334  我修改损失函数为1-dice，现在运行成功，iou在0.98左右

**Comment by xq141839** [comment]
[jiokul]：修改损失函数为1-dice，现在运行成功，iou在0.98左右
