### ISSUE TITLE
Can you provide the preprocessed data sets of SegPC-2021 and 2018 Data Science Bowl?

### ISSUE THREAD

**Issue by Pang-b0** [xq141839/DCSAU-Net#22]
Hello, author. Congratulations on such a good result. I am very interested in your paper. However, in the process of reproducing the results, I found that the number of data sets I downloaded from SegPC-2021 and 2018 Data Science bowl is different from that given in your paper. So I want to ask you for a preprocessed SegPC-2021 and 2018 Data Science bowl data set in the paper. E-mail 1399308695@qq.com, I would appreciate it.

**Comment by xq141839** [comment]
Thanks for your attention to our work. You can download the data from this link: [https://t.wss.ink/f/c1wmqlhxhfn](within 24h)

**Comment by Pang-b0** [comment]
Thank you very much for your reply, but I found that segpc-2021 in the link has only 449 folders, and the total number of files mentioned in the paper is 498, test is 49, and train and valid are 449. Is there any omission? Can we add a qq or vx exchange? I would be very grateful, QQ: 1399308695.
