### ISSUE TITLE
train

### ISSUE THREAD

**Issue by FRC1221** [xq141839/DCSAU-Net#24]
data_split_csv.py对images划分，那masks需要划分吗，然后训练报错找不到masks
![IMG_20240122_155517](https://github.com/xq141839/DCSAU-Net/assets/141699693/1669b60f-7845-442f-baf6-9ac2ac789269)

**Comment by xq141839** [comment]
应该是你的image名字和mask图片名字不一样吧，数据加载的py里默认这两个文件名是一样的，就像我readme里写的数据格式那样，你可以改一下数据加载里的文件或者把mask和image的名字对齐一下。

**Comment by FRC1221** [comment]
名称是对齐的的
![IMG_20240123_123641](https://github.com/xq141839/DCSAU-Net/assets/141699693/9388b280-4df0-4f3c-8faf-62f8a95de166)
请看看我的划分.py和train.py，填的是否正确
![IMG_20240123_123738](https://github.com/xq141839/DCSAU-Net/assets/141699693/60977f1a-b593-4bb0-84e5-85cc41fa4529)
![IMG_20240123_123814](https://github.com/xq141839/DCSAU-Net/assets/141699693/84697509-9d3e-493a-9202-752981337fb8)

**Comment by xq141839** [comment]
哦哦哦我代码里名字会带文件后缀，你这个应该是jpg和png不一样的关系。可以都转化成png或者数据加载代码里改一下

**Comment by FRC1221** [comment]
thank，ok
