### ISSUE TITLE
多分类数据集的处理问题

### ISSUE THREAD

**Issue by naadurian** [xq141839/DCSAU-Net#28]
您好，我想请教一下对于data-science-bowl-2018和TCIA_SegPC_dataset数据集来说，这种多分类问题我该怎么处理数据呢，我现在只是改了train.py文件里的
train_dataset = multi_classes(args.dataset,train_files, get_train_transform())
val_dataset = multi_classes(args.dataset,val_files, get_valid_transform())这两条语句，改为了multi_classes，但是一直有各种错误。

如果作者有处理好的这两个多分类数据集的数据的话可以给我发一下吗，非常感谢！！
我的邮箱2675316384@qq.com

**Comment by xq141839** [comment]
你好，data-science-bowl-2018数据集输入二分类问题也就是binary segmentation。其次需要处理多分类任务的时候不仅需要改写dataloader的模式，还需要更改loss的计算方式，默认的loss应该是针对二分类的任务，这两个数据我将稍后发给你

**Comment by ttjjyys** [comment]
> 你好，data-science-bowl-2018数据集输入二分类问题也就是二进制分割。其次需要处理多分类任务的时候不仅需要改写dataloader的模式，还需要更改loss的计算方式，默认的loss应该是针对二分类的任务，这两个数据我将稍后发给你

您好，可以麻烦您发我一份Seg·PC2021的数据集吗，找到的都不是原标签，我的邮箱是2453499915@qq.com,谢谢您

**Comment by 18834114892** [comment]
> 你好，data-science-bowl-2018数据集输入二分类问题也就是binary segmentation。其次需要处理多分类任务的时候不仅需要改写dataloader的模式，还需要更改loss的计算方式，默认的loss应该是针对二分类的任务，这两个数据我将稍后发给你

您好，作者，处理多分类的数据代码可以也发我一下吗，邮箱2453499915@qq.com     谢谢

**Comment by ttjjyys** [comment]
> 你好，data-science-bowl-2018数据集输入二分类问题也就是binary segmentation。其次需要处理多分类任务的时候不仅需要改写dataloader的模式，还需要更改loss的计算方式，默认的loss应该是针对二分类的任务，这两个数据我将稍后发给你

您好，处理SegPC2021多分类数据集的代码也可以发我一下吗，我的邮箱是2453499915@qq.com    万分感谢，自己调整了半天整了一堆错出来

**Comment by naadurian** [comment]
你好，处理数据集的代码我没有，我当时是找作者要了处理后的数据直接用的&nbsp;


嘿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月24日(星期二) 下午2:55
收件人: "xq141839/DCSAU-Net";
抄送: "Author";
主题: Re: [xq141839/DCSAU-Net] 多分类数据集的处理问题 (Issue #28)






你好，data-science-bowl-2018数据集输入二分类问题也就是binary segmentation。其次需要处理多分类任务的时候不仅需要改写dataloader的模式，还需要更改loss的计算方式，默认的loss应该是针对二分类的任务，这两个数据我将稍后发给你

***@***.***    万分感谢，自己调整了半天整了一堆错出来

&mdash;

**Comment by ttjjyys** [comment]
> 你好，处理数据集的代码我没有，我当时是找作者要了处理后的数据直接用的&nbsp; 嘿 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月24日(星期二) 下午2:55 收件人: "xq141839/DCSAU-Net"; 抄送: "Author"; 主题: Re: [xq141839/DCSAU-Net] 多分类数据集的处理问题 (Issue #28) 你好，data-science-bowl-2018数据集输入二分类问题也就是binary segmentation。其次需要处理多分类任务的时候不仅需要改写dataloader的模式，还需要更改loss的计算方式，默认的loss应该是针对二分类的任务，这两个数据我将稍后发给你 ***@***.*** 万分感谢，自己调整了半天整了一堆错出来 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

谢谢您的回复，我再试试

**Comment by ttjjyys** [comment]
> 您好，我想请教一下对于data-science-bowl-2018和TCIA_SegPC_dataset数据集来说，这种多分类问题我该怎么处理数据呢，我现在只是改了 train.py 文件里的 train_dataset = multi_classes（args.dataset，train_files， get_train_transform（）） val_dataset = multi_classes（args.dataset，val_files， get_valid_transform（））这两条语句，改为了multi_classes，但是一直有各种错误。
> 
> 如果作者有处理好的这两个多分类数据集的数据的话可以给我发一下吗，非常感谢！！ 我的邮箱 [2675316384@qq.com](mailto:2675316384@qq.com)

想再问下您，最后关于多分类的代码都修改了哪几处呢，谢谢

**Comment by naadurian** [comment]
你好，我当时没改通多分类代码，所以最后没有使用多分类数据集了，




嘿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xq141839/DCSAU-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xq141839/DCSAU-Net] 多分类数据集的处理问题 (Issue #28)






您好，我想请教一下对于data-science-bowl-2018和TCIA_SegPC_dataset数据集来说，这种多分类问题我该怎么处理数据呢，我现在只是改了 train.py 文件里的 train_dataset = multi_classes（args.dataset，train_files， get_train_transform（）） val_dataset = multi_classes（args.dataset，val_files， get_valid_transform（））这两条语句，改为了multi_classes，但是一直有各种错误。

如果作者有处理好的这两个多分类数据集的数据的话可以给我发一下吗，非常感谢！！ 我的邮箱 ***@***.***

想再问下您，最后关于多分类的代码都修改了哪几处呢，谢谢

**Comment by ttjjyys** [comment]
> 你好，我当时没改通多分类代码，所以最后没有使用多分类数据集了，
> 
> 嘿
> ***@***.***
> 
> &nbsp;
> […](#)

谢谢，祝您科研顺利
