### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by geek-APTX4869** [xq141839/DCSAU-Net#29]
训练ClinicDB时报错
```
File "/home/fanyu/DCSAU-Net-main/loss.py", line 64, in forward
    intersection = (inputs * targets).sum()                            
                    ~~~~~~~^~~~~~~~~
RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 3
```

**Comment by xq141839** [comment]
你好，这种情况你应该先打印出两个参数的维度看一下是否对其

**Comment by QH-Jia** [comment]
> 训练ClinicDB时报错
> 
> ```
> File "/home/fanyu/DCSAU-Net-main/loss.py", line 64, in forward
>     intersection = (inputs * targets).sum()                            
>                     ~~~~~~~^~~~~~~~~
> RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 3
> ```

请问你跑通了吗

**Comment by xq141839** [comment]
跑通了啊，ClinicDB应该是肠胃镜息肉分割数据集，你看一下是否建立数据集的时候有问题

**Comment by QH-Jia** [comment]
奇怪，数据集不就是正常下载下来就可以用吗，是需要在程序里修改什么东西吗，你看我在运行csv程序时就没问题，后边怎么还有张量上的问题 
---- Replied Message ----
FromQing ***@***.***>Date7/14/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [xq141839/DCSAU-Net] RuntimeError (Issue #29)
跑通了啊，ClinicDB应该是肠胃镜息肉分割数据集，你看一下是否建立数据集的时候有问题

**Comment by xq141839** [comment]
你用是数据集输入是.tif格式吗，如果是的话我建议先转成png格式。我根据你的报错猜测是targets也就是label你读取的是 batch x 256 x 256 x 3格式，而网络输出的是 batch x 1 x 256 x 256, 所以推断你的label在数据集创建的时候有问题，看一下是否在dataloader的时候运行正常。

**Comment by QH-Jia** [comment]
可以加你个QQ或者微信吗，可以方便联系一下
QQ：2979655736
微信：jqh15824955578
---- Replied Message ----
FromQing ***@***.***>Date7/14/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [xq141839/DCSAU-Net] RuntimeError (Issue #29)
你用是数据集输入是.tif格式吗，如果是的话我建议先转成png格式。我根据你的报错猜测是targets也就是label你读取的是 batch x 256 x 256 x 3格式，而网络输出的是 batch x 1 x 256 x 256, 所以推断你的label在数据集创建的时候有问题，看一下是否在dataloader的时候运行正常。

**Comment by geek-APTX4869** [comment]
> 你用是数据集输入是.tif格式吗，如果是的话我建议先转成png格式。我根据你的报错猜测是targets也就是label你读取的是 batch x 256 x 256 x 3格式，而网络输出的是 batch x 1 x 256 x 256, 所以推断你的label在数据集创建的时候有问题，看一下是否在dataloader的时候运行正常。

mask = io.imread(mask_path)读取出的是3维

**Comment by xq141839** [comment]
原版的数据集是tif格式，我建议可以去kaggle上找别人已经处理好的png图片会比较好一点。如果是原数据集的话可能会要再预处理一下

**Comment by ttjjyys** [comment]
> > 你用是数据集输入是.tif格式吗，如果是的话，我建议先转成png格式。我根据你的报错猜测是targets也就是label你读取的是 batch x 256 x 256 x 3格式，而网络输出的是 batch x 1 x 256 x 256， 所以推断你的label在数据集创建的时候有问题，看一下是否在dataloader的时候运行正常。
> 
> mask = io.imread（mask_path）读取出的是3维

您好，SegPC2021数据集属于多类分割，在跑SegPC2021时，代码有需要改动的地方吗

**Comment by ttjjyys** [comment]
您好，SegPC2021数据集属于多类分割，在跑SegPC2021时，代码有需要改动的地方吗
