### ISSUE TITLE
Could you please share the code of comparison model in the paper

### ISSUE THREAD

**Issue by MOONWZ** [xq141839/DCSAU-Net#3]
Thank you for your contribution to relevant work. Could you please share the code of comparison model in the paper, such as ResUnet++ doubleu-net TransUnet levit-unet, which would be very helpful to me

**Comment by xq141839** [comment]
Hello, all of the models are compared by using eval_binary.py and eval_multiple.py, so I am a little bit confused about your requirement. Do you need the training code of other models?

**Comment by MOONWZ** [comment]
yes, I have some problems related to code in another problem. Could you please help me solve them
