### ISSUE TITLE
RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 4

### ISSUE THREAD

**Issue by MOONWZ** [xq141839/DCSAU-Net#4]
请问我该如何解决这个问题，我使用的是Kavisr数据集，代码没有任何改动，但是出现了这个错误
Epoch 0/149
----------
Traceback (most recent call last):
  File "D:\paperin\a_new_road\DCSAU-Net-main\train.py", line 176, in <module>
    model_ft, Loss_list, Accuracy_list = train_model(model_ft, criterion, optimizer_ft, exp_lr_scheduler,
  File "D:\paperin\a_new_road\DCSAU-Net-main\train.py", line 85, in train_model
    loss = criterion(outputs, labels)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\paperin\a_new_road\DCSAU-Net-main\loss.py", line 65, in forward
    intersection = (inputs * targets).sum()                            
RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 4

这个地方调试的inputs是Tensor(8, 1, 256, 256)，但是targets是Tensor(8, 1, 256, 256, 3),请问是需要修改什么还是我数据集划分的问题
数据集划分
 ├── data
          ├── images
                ├── cju0qkwl35piu0993l0dewei2.png
                 .......
          ├── masks
                ├── cju0qkwl35piu0993l0dewei2_segmentation.png
                 .......

**Comment by xq141839** [comment]
那个mask和mask的图片名应该是相同的，这样才能对应起来，可能你需要把_segmentation那部分去掉，有问题可以加我企鹅1015167278，GitHub可能回复不及时，抱歉

**Comment by xq141839** [comment]
模型那问题你可以给我个邮箱我发你或者加我企鹅我给你

**Comment by 1789000076** [comment]
intersection = (inputs * targets).sum()                            
RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 4
您好，我用的是肠息肉数据集。
![image](https://user-images.githubusercontent.com/100548388/202998847-0b6da10c-6535-48ef-8b41-dc10da879d8e.png)
input的格式是（2，1，256，256）
targets的格式是（2，1，256，256，3）
我的邮箱是2106639131@qq.com，QQ是2106639131。
希望您能抽空看一下！十分感谢！
