### ISSUE TITLE
Can you provide the SegPC-2021 dataset you have processed?

### ISSUE THREAD

**Issue by jane442** [xq141839/DCSAU-Net#5]
Excellent work！can you provide the labels of the SegPC-2021 dataset you processed? My email is 2010321073@qq.com, I would be very grateful if you can provide it

**Comment by kimo20200** [comment]
Hello, I have sent the download link to you, please check your email. Thank you a lot.

**Comment by mustansarfiaz** [comment]
Hi,

Excellent work！
Could you provide the labels of the SegPC-2021 dataset you processed? My email is [mustansar.fiaz@gmail.com](mustansar.fiaz@gmail.com), I would be very great.

Regards:

**Comment by 18834114892** [comment]
> 你好
> 
> 干得漂亮！您能否提供您处理的 SegPC-2021 数据集的标签？我的电子邮件 [mustansar.fiaz@gmail.com](mustansar.fiaz@gmail.com)，我会很棒。
> 
> 问候：
您能否提供您处理的 SegPC-2021 数据集的标签？我的电子邮件是2453499915@qq.com,         Thank you

**Comment by ttjjyys** [comment]
您好，您能否提供您处理的 SegPC-2021 数据集的标签？我的电子邮件是 [2453499915@qq.com](mailto:2453499915@qq.com)， 谢谢
