### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Zrs1171757736** [xq141839/DCSAU-Net#7]
Excuse me, I want to train the ISIC Task 1 official dataset. What should the directory format of the data be? I store the data according to the directory structure of the data you give , and execute the data_ split_ csv，The test machine and training set cannot be divided into csv files .

**Comment by xq141839** [comment]
Hello, thanks for your attention to our work. Can you provide your directory format of the dataset?

**Comment by Zrs1171757736** [comment]
![2](https://user-images.githubusercontent.com/101089871/202982479-572025ce-4a51-4552-9a2c-3686bab2a41f.jpg)
![3](https://user-images.githubusercontent.com/101089871/202982581-f852c492-ebea-4795-a8e3-fd820f42a51e.jpg)
您看一下。

> 您好，感谢您对我们工作的关注。你能提供数据集的目录格式吗？

**Comment by xq141839** [comment]
images文件夹中文件名和格式应与masks文件夹中的文件是的一致。比如您这个masks文件夹中的第一个文件应改为ISIC_000000.png，以此类推。另外执行数据分割的代码时，应该输入有包括png文件的文件夹路径，比如‘data/images/’。

**Comment by Zrs1171757736** [comment]
> images文件夹中文件名和格式应与masks文件夹中的文件是的一致。比如您这个masks文件夹中的第一个文件应改为ISIC_000000.jpg，以此类推。另外执行数据分割的代码时，应该输入有包括png文件的文件夹路径，比如‘data/images/’。

好的，我修改一下，非常感谢

**Comment by xq141839** [comment]
没事，有问题可以再问我哦：）
