### ISSUE TITLE
RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 4

### ISSUE THREAD

**Issue by 1789000076** [xq141839/DCSAU-Net#8]
intersection = (inputs * targets).sum()
RuntimeError: The size of tensor a (256) must match the size of tensor b (3) at non-singleton dimension 4
您好，我用的是肠息肉数据集。

![image](https://user-images.githubusercontent.com/100548388/203000174-fa933bd4-d4c4-4a3d-a4e7-f985ee482d77.png)

input的格式是（2，1，256，256）
targets的格式是（2，1，256，256，3）
我的邮箱是2106639131@qq.com，QQ是2106639131。
希望您能抽空看一下！十分感谢！

**Comment by xq141839** [comment]
您好，虽然不知道您的数据集具体长什么样，但是输出维度应该是 batchsize x 分类类别数量 x H x W。你可以把这里的第二维（1）给去掉然后把最后一维（3）换到前面来，具体可以使用 .view 或者 permute 函数。另外您这个输入也有点奇怪，一般通常讲输入都是RGB图片，所以inputs的第二维也应该是3而不是1。

**Comment by 1789000076** [comment]
![image](https://user-images.githubusercontent.com/100548388/203012493-730d8008-c753-4e77-8872-6ac3dd79c812.png)
您好！数据集是这样的，直接用的png格式，跟您的Readme中Dataset的要求一样的。

**Comment by xq141839** [comment]
你这个target是模型直接输出的结果吗还是做过别的处理了？另外这个看上去像是cvccdb数据集，它应该原来是.tif格式，你可以看的png维度是不是和原来的一样。

**Comment by 1789000076** [comment]
您好！target是模型直接输出的。此外，确实是CVCCDB数据集。下载之后有PNG这个目录，就直接用这个来训练。您之前是用.tif格式训练的吗？

**Comment by xq141839** [comment]
我是用tif来训练，你可以看看图片进模型时候的维度，应该是3维的，你这个进去1维的有点奇怪，输出你可以看看定义模型时候的参数有没有错：
` model_ft = DCSAU_Net.Model(img_channels = 3, n_classes = 1)`

**Comment by 1789000076** [comment]
好的，谢谢您。

**Comment by xq141839** [comment]
没事，有别的问题可以再来问我：）

**Comment by renxiaosa00** [comment]
您好，我的输入图片大小不是固定的256*256，而是512*400（400这个数字是围绕400大小上下的宽度），这样能做分割吗？

**Comment by xq141839** [comment]
可以的，修改一下resize的大小应该就行
