### ISSUE TITLE
there is no predict.py?

### ISSUE THREAD

**Issue by xiedajiao1** [xq141839/DCSAU-Net#9]
can you update the predict.py to drow the the mask image,please!thank you very much!

**Comment by xq141839** [comment]
Actually, the code of generating mask images has been involved in the eval_binary.py and eval_multiple.py. 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/98734126/204753046-8ce28ac7-4064-470b-b48a-6427bb9ca6c2.png">
